# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  dart = {
    pname = "dart";
    version = "2.17.6";
    src = fetchurl {
      url = "https://storage.googleapis.com/dart-archive/channels/stable/release/2.17.6/sdk/dartsdk-linux-x64-release.zip";
      sha256 = "sha256-+DfzhWA6HPsU3bfdDNZIILKXZGYmvbaJzPwyePqDsrE=";
    };
  };
  flutter = {
    pname = "flutter";
    version = "3.0.5";
    src = fetchurl {
      url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.5-stable.tar.xz";
      sha256 = "sha256-aRoSXOeQ+vijRTa5vSmMMa2/LSVo/JOE4tQ6acXB1sw=";
    };
  };
}
